// ignore_for_file: depend_on_referenced_packages

export 'package:occasional_pockets/View/Screens/Home view/splash_view.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:get/get.dart';
export 'package:occasional_pockets/View/Common%20Functions/navigator_screec.dart';
export 'package:flutter/material.dart';
export 'package:occasional_pockets/View/Common%20Functions/app_color.dart';
export 'View/Common Widgets/common_service_card.dart';
export 'Controller/AdminControllers/admin_platinum_controller.dart';
export 'package:occasional_pockets/View/Common Widgets/appbar_decoration.dart';
export 'package:occasional_pockets/Controller/ManageControllers/basic_form_controller.dart';
export 'package:image_picker/image_picker.dart';
export 'package:occasional_pockets/View/Common Functions/image_picker.dart';
export 'Controller/ManageControllers/premium_form_controller.dart';
export 'Controller/ManageControllers/platinum_form_controller.dart';
export 'Controller/about_us_controller.dart';
export 'package:occasional_pockets/View/Screens/About/about_us.dart';
export 'package:cloud_firestore/cloud_firestore.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:occasional_pockets/View/Screens/Authentication/marquee_form.dart';
export 'package:flutter_spinkit/flutter_spinkit.dart';
export 'Controller/ManageControllers/makeown_form_controller.dart';
export 'Controller/AdminControllers/admin_makeown_controller.dart';
export 'Controller/UserController/user_conroller.dart';
export 'Controller/UserController/user_package_detail.dart';
export 'Controller/UserController/user_makeown_detal.dart';
export 'package:flutter_spinkit/flutter_spinkit.dart';
export 'View/Common Widgets/loader_widget.dart';
export 'Controller/UserController/user_request_controller.dart';
